### ISSUE TITLE
ProjectE Repair Talisman repairs Pets

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#14]
Need to find a way to disable, if possible

**Comment by capnkirok** [comment]
Compat required

**Comment by OracleofWuffing** [comment]
I don't know if this helps, but according to this old issue on ProjectE's github, the Talisman of Repair just checks isRepairable, a method that doesn't require ProjectE compatibility, in order to determine if the Talisman of Repair functions on the item.

https://github.com/sinkillerj/ProjectE/issues/602

**Comment by capnkirok** [comment]
Yeah, unfortunately, using this flag also prevents pet feeding from working properly. Need to find another workaround.

**Comment by capnkirok** [comment]
The best solution is to create a new durability bar based on Item NBTData.

**Comment by capnkirok** [comment]
Yes, figured out how to keep this from happening. Will be fixed in 1.4.0
