### ISSUE TITLE
(v1.49) April Fools pet deletes blocks below ALL players on the server

### ISSUE THREAD

**Issue by ariosos** [capnkirok/Inventory-Pets#154]
Using the Foolcraft modpack, one player made an April Fools pet, which not only took out blocks below them, but also blocks below me (destroying some chests and other htings in the process). Not sure if it's supposed to affect all players...

**Comment by capnkirok** [comment]
Yes.... it is. You can disable in the config... 
https://twitter.com/Purplicious_Cow/status/848135980913655808

**Comment by ariosos** [comment]
You're so evil. :p (and I thought Chance Cubes were evil)

But yeah, looks like that config option is being changed.

**Comment by capnkirok** [comment]
I'm debating removing the affects all players thing. I was young and naive when I dreamed this one up 😆. It was not supposed to be destructive....  deleting chests... bad.

**Comment by capnkirok** [comment]
I've changed this so if you have mob griefing turned off, then both the 'drop' prank and the switch armor for rotten flesh prank will no longer occur.

**Comment by DoomSquirter** [comment]
even tho this is a closed issue, I just want to comment that having the player be affected by whatever the inevitable result, is bad in and of itself, having ALL ppl on a server affected by it is a truly dick move.  I just made this pet and missed my farming station by one block *whew* disaster averted.  but, another person was one block shy of destroying our group's entire refined storage system.  Come on!  that's really not funny unless you are a reoccurring guest star on jackass.

**Comment by capnkirok** [comment]
Yes, you necro'd a closed issue with a new suggestion (does that make us even?)

Well, I would strongly recommend you turn off the April Fool pet in the config, if you are using it with Refined Storage. 

- But... I can also add a config toggle so that the April Fool pet only affects the original player.
- And I think I'm going to change it so it only works for the first week of April. One month is way too long for such an unpredictable pet.

**Comment by DoomSquirter** [comment]
so, options here.  tag onto existing issue that exactly matches my concern, or create a new superflous redundant issue replicating exact same concern.  nah man.

first off, I love the mod.  I do.  playing craft of the titans and after an issue with jetpacks that makes them useless, I spent an hr searching for a cloud pet for flight and found one and am extremely happy.  I absolutely love the anvil pet and spawn temp anvils when I'm lonely cause it's the best.

but this ?  no.  there's a line and it's totally crossed when you grief things.  april fools or no april fools.  And yeah, good that there's a config option, but if admin doesn't know of the problem, there's always going to be a first time that it happens that's potentially going to be a complete disaster.  Again, doing it to the person that used the thing is bad.  doing it to everyone on server is really unfathomable.  By default it should only affect the player, in fact doing otherwise is extremely bad form I think.

rotten flesh for armor?  fine.  that's a joke.  do it to the server for all I care but destroying blocks, etc?  No please no.  The guilt I feel at this point in time for affecting everyone just now is extreme right now.

**Comment by capnkirok** [comment]
Yeah, I try to warn people, but it's not enough. I hear you. I do like the randomness of it, and the danger. But on an established server, it can be extremely painful. It's really just supposed to be fun. I didn't really think about that when I coded this 14 months ago.

I could always flip it around so the drop (and rotten flesh armor switch) is only enabled if you choose to enable it. Or I could just shut those options down entirely. I certainly don't like making people upset. It's a lot of fun for many people... but not for people who don't know.

The Rotten Flesh Armor... so... this happened last year... Player... flying in the Nether... over lava... inventory full... bye bye Draconic armor.

**Comment by b0bst3r** [comment]
Haha Doom and you thought I was evil giving Railcraft's Firestone as a HQM reward :D

**Comment by DoomSquirter** [comment]
as a comparison, the chance cubes have a almost identical kind of troll.  you open it, it makes a hole under you, 5x5 down to bedrock, you fall, but then it closes back up again, haha you suffocated lol  

I think the problem really comes down to this.  Chance cubes?  You KNOW that you are taking your life in your hands each and every time you open one.  The potential disaster is a known quantity.  

Inventory pets tho?  Cute and cuddly, warm and soft, to the rescue friends that live a happy and cheerful existence in my pocket.  (don't make it more than it is ok? lol )  Having something suddenly turn on you and do something disasterous seems jarring and not in line with the theme of the mod.  Pranks?  Sure.  But any hint of any kind of griefing doesn't seem right to me.  

The doing it to everyone on the server alongside you tho, I can't see how that's ever a good idea really unless it's innocuous like fireworks over their head or sounds played or something really non threatening.  

One of my favorite trolls from chance cube is when it renames a random armor piece and gives it a little legend.  or maybe create an effect that makes the person bounce uncontrollably, or temporarilly choose a random skin for the person a pile of poo, bannana, monkey, whatever.  they might not know it happened since others would have to see it.  

Things like that are pranks.  IMHO, destructive things are not.  If the person that's having the prank pulled on them can laugh at it then it's a prank, plain and simple.  Anything else is assault/griefing and is the best way to create a evil villain, hell bent on revenge.... 

edit: oh and yeah, I'd assume that any kind of damaging type jackass level pranks should be opt-in, not enabled by default. Let the pack maker take responsibility for enabling these options and let them deal with any backlash that ensues.

**Comment by capnkirok** [comment]
Ok, i have added a new config called Enable April Fool Grief Pranks. This will be set to FALSE by default. It excludes the DROP and the Rotten Flesh for Armor switch.

Now that it's May, you can trust this message :)
