### ISSUE TITLE
Ender pet error (conflict with Twilight Forest?)

### ISSUE THREAD

**Issue by AnyarRay** [capnkirok/Inventory-Pets#294]
Minecraft crashed twice in 5 minutes the first time I used the Ender pet. I haven't tested any more though, but I was using the Ender minions in creative against some Twilight Forest mobs.

The error log was generated by the VanillaFix mod and can be found here:
https://paste.dimdev.org/rexaqafifo.mccrash
or the text-only version:
https://paste.dimdev.org/raw/rexaqafifo

**Comment by capnkirok** [comment]
The line of code in question:
`if (this.lastEntityToAttack != null && this.lastEntityToAttack != entityplayer.getLastAttackedEntity());`

Something in the second condition is resulting in Null when you attack Twilight Forest mobs, so either:
miniquantumenderman
entityplayer
getLastAttackedEntity()

Which is odd since all three of them should have results. However, I can add another check.

**Comment by capnkirok** [comment]
Ok, added in more null checks. Will be in next release.
