### ISSUE TITLE
Game crash involving cow pet making world unloadable

### ISSUE THREAD

**Issue by AdaraChristine** [capnkirok/Inventory-Pets#307]
inventorypets-1.12-2.0.1
Forge 14.23.5.2836

I have a player that had a game crash that would not let him load the world again unless Inventory Pets was disabled.

https://pastebin.com/eT961Tyr

**Comment by capnkirok** [comment]
The bug indicates that the player's cow pet is causing a crash because it can't loop through the player's hotbar. It's going to be some time before I can make any kind of fix (due to availability of the code). Is there a way to purge that item from the player's inventory?

Are you using any of the other mods to modify the hotbar size / inventory?

PC

**Comment by AdaraChristine** [comment]
"Are you using any of the other mods to modify the hotbar size / inventory?"
Not that i know of. Here is the mod list for the pack
https://minecraft.curseforge.com/projects/mystical-village-2/relations/dependencies

Do you think its just the cow pet? If so i can disable it in the pack.

**Comment by capnkirok** [comment]
This should be fixed in the next release.
