### ISSUE TITLE
Cannot enchant with enchanting table

### ISSUE THREAD

**Issue by Bacondk** [capnkirok/Inventory-Pets#326]
I dont know what is causing this but every time i open and and click enchant item it dosent enchant

**Comment by Bacondk** [comment]
[Uploading Video.zip…]()

**Comment by Anarkitty** [comment]
I'm experiencing the same thing. It seems like it's working, the pet opens, the item is placed in the slot, the options for enchantments show up, but when actually clicking on the enchantment to apply it there is no response.

My server is running Inventory Pets 2.0.3 with the R.A.D. modpack.

**Comment by capnkirok** [comment]
Will look into  it. Thanks for the report.

**Comment by Ktar5** [comment]
Any update? I'd love to use this pet.

**Comment by JoelZBub** [comment]
Here is video confirmation of this issue, using *only* InventoryPets-1.12-2.0.3 , no other mods.
https://youtu.be/V-Dfp5WCD1g
Forge version is 14.23.5.2838
EDIT : The above video has the wrong food in inventory for the pet ( lapis instead of lapis nuggets).  
The correct food for the pet is shown in this video:
https://youtu.be/LLMieB_Eb94
Notice how the Lapis Nuggets go down one each time the Pet GUI is opened, but no enchantment happens when clicking the enchant buttons.

**Comment by JoelZBub** [comment]
Should we just disable this pet in our modpack?

**Comment by capnkirok** [comment]
Hey guys, sorry for late reply. Looks like there's a client/server de-sync happening. I'll work on a fix... you can disable it for now (and re-enable when working).

**Comment by JoelZBub** [comment]
Thanks for the reply.

**Comment by capnkirok** [comment]
Ok everyone, you are not going to believe this:

The Enchanting Table Pet works, it's just that the location of the UI is incorrect. If you hover your mouse slightly left and up from the GUI, you can make your selection and choose your enchant. I have no idea how this happened, as I haven't changed the GUI.

At any rate, you can use that trick above for now. I am working on a fix.

**Comment by capnkirok** [comment]
Ok fixed it. Look for the 2.0.4 update soon.

**Comment by JoelZBub** [comment]
Thank you so much for the fix. Looking forward to it.
