### ISSUE TITLE
PROBLEM WITH RESIZING POTION MOD!

### ISSUE THREAD

**Issue by Nickyimbo** [capnkirok/Inventory-Pets#356]
https://pastebin.com/MkXGRHz2 I really want to put this mod on my server but i got this problem!

**Comment by Nickyimbo** [comment]
This happen whenever i install the resizing potion mod, in their discord they told me to ask to inventory pets devs

**Comment by Nickyimbo** [comment]
This happen when i install the resizing potion mod

**Comment by capnkirok** [comment]
That is really strange. This is saying it can't load a specific event 'Arrow Loose Event' at launch. What would the resizing potion mod have to do with that event?

If you remove resizing potion mod, then you don't see the error?

**Comment by Nickyimbo** [comment]
If i remove the resizing potion i dont have that error, i really dont know why actually they said that nothing should be incompatible with this mod

**Comment by capnkirok** [comment]
I just tested on the same version of forge you are using and had no problems.

![image](https://user-images.githubusercontent.com/9628379/81240792-647e6600-8fd6-11ea-9082-22fa1f005636.png)

Of course, I don't have all the mods you have and I'm not using Sponge. Have you asked the Sponge folks? There is nothing wrong with that particular line of code in the main class. It really is just a loader:

`MinecraftForge.EVENT_BUS.register(new InstaShotHandler());`

The error says "java.lang.NoClassDefFoundError" which usually happens when you are trying to load something on the client side that is server only... which is not the case here. We're in the main class and this event is not client side.
