### ISSUE TITLE
[1.16.4] configs and worldgen quirks

### ISSUE THREAD

**Issue by bessiq** [capnkirok/Inventory-Pets#378]
InventoryPets-1.16-2.0.9
Forge 35.1.28

Hi there,

Thanks for porting this to 1.16.4! I've changed some of the configs in `config\inventorypets-common.toml`, but they don't seem to be working:
- `disableCrafting = true` - all pets are still craftable
- `petsEatWholeItems = true` - I think this means pets eat ingots/gems instead of the nuggets? (e.g. emerald instead of emerald nugget, iron ingot instead of nugget, etc.). Tested with anvil pet and he still prefers iron nuggets lol.
- `disableNormalNuggetsRecipes = true` - this actually might be working - does it disable all nugget recipes from this mod, or only recipes for vanilla nuggets (e.g. iron, gold)?
- `illuminatiCooldown = 3` - the comment says this is in minutes, but this makes the cooldown 30 minutes, not 3. I haven't checked but I assume the default value of 1 makes the cooldown 10 minutes.

The only other configs I changed seem to be working - the ones related to dungeon frequency.

As far as worldgen:
I've been unable to find any treetop chests. If I do a /locate for those it takes me to a spot where there is no tree, so I check nearby trees and still cannot find a chest. I went and found vanilla biomes and checked a bunch of different vanilla trees, since idk if modded trees are supported. I also went all the way down to bedrock in case some mod adds a tree down there (Quark does iirc).

I've found all the dungeons, but I've noticed some possibly unintended behavior:
- SeaCave dungeons sometimes spawn in sets of 2-4, in a grid. They also appear to be able to spawn on water blocks. This makes them spawn pretty close to the ocean surface at times. (Screenshots below.)

- I think I saw an Underground dungeon set of 4 once also, but I can't remember now. I did find one that was spawning Wither Skeletons, but that might be intended. 😀 

![2021-01-03 (2)](https://user-images.githubusercontent.com/7315505/103488325-96500280-4dd9-11eb-8595-c1b660b5d848.png)
![2021-01-03 (3)](https://user-images.githubusercontent.com/7315505/103488360-d911da80-4dd9-11eb-9402-153e4d6a739b.png)

Still a very fun mod and glad I could add it to my pack!

**Comment by capnkirok** [comment]
Ah, I love this detailed report. 

Yeah, I can't get dynamic crafting to work yet, so that config does nothing. I'll remove that config until I get it in place. Illuminati Cooldown is fixed, you'll see in next release. The others should be working, so I'll check them.

WorldGen in 1.16.4 is all new, so working out the kinks. Spacing is a real problem, even with the new 'separation settings'. Water used to be more opaque in 1.12... I agree these are a bit too easy to find now.

Diving into this now as I was hoping to get an update out today. Let me know if you run across anything else.

**Comment by bessiq** [comment]
Thanks for the reply! I am a modpack..."hobbyist" (lol), but it has helped me learn a few things about modded MC. Not as much a true mod dev, though!

I disabled the pet recipes with a KubeJS script, but just thought I'd let you know. And I have quite a few structure mods, and trust me, they have all struggled to some degree in 1.16.4. I don't envy you! Also, I did have Night Vision in the screenshots, so it  affected visibility obviously.

Oh, I forgot to mention earlier, but the anvil pet is missing the lang entry when you spawn it. I'll reply with anything else I notice. Thanks again!

**Comment by capnkirok** [comment]
Also, treetop chests are tricky. They are actually structures, not trees. And they spawn using the vanilla biome categories (which other mods should use as well). They look like trees and spawn where you would expect the last log block to be before the leaves. Best way to find them is to fly overhead (with a Cloud Pet) and spy down.

**Comment by capnkirok** [comment]
Ok, these should be fixed in the next release. I didn't see any issues with the Illuminati Pet timer, since I made updates. The Illuminati Pet is now based on World Time, so if there was any manual time manipulation, that would have caused an issue. So if it was night time, and you manually reset it to day, it would have resulted in an increase close to 30 minutes, since Minecraft doesn't advance the day with manual manipulation.

**Comment by bessiq** [comment]
Cool, sounds good. I do switch to day/night quite a bit when testing stuff, and did notice it doesn't advance the day. So your explanation makes sense. And I'll keep looking for treetop chests!
