### ISSUE TITLE
double chest pet deleting my item

### ISSUE THREAD

**Issue by hatchetkills** [capnkirok/Inventory-Pets#431]
So I use the double chest pet in my no cheats survival world but i logged on today and everything was missing from the pets i had in my inventory, i use them while mining but this is kinda weird

**Comment by capnkirok** [comment]
So sorry to hear this Ravi. A bug was recently discovered in the way Forge and Minecraft work together on storing items using capabilities. I have to completely rewrite my code since I can no longer use this method.

The bug occurs primarily if you switch to Creative Mode on a Server and move the item to a new slot. It can also occur after a server re-start. Super annoying. You can learn more about it here;

#407

**Comment by hatchetkills** [comment]
but i don't have cheats on, im not going into creative

**Comment by capnkirok** [comment]
Have you re-started or re-joined the server? Same issue with the code. Again, sorry this happened (though it is not my code that is the problem). All of the code must be re-written just as Botania and Backpacks and countless others have had to do.

**Comment by hatchetkills** [comment]
i left and rejoined the world multiple times and it also deleted two other pets i had inside it
