### ISSUE TITLE
Enderman Pet Needs A Nerf

### ISSUE THREAD

**Issue by crimsonDestroyer** [capnkirok/Inventory-Pets#467]
It's a basic, easy-to-obtain pet, that, in exchange for obsidian nuggets (which are extremely easy to obtain once you can mine obsidian), makes you immortal. Completely immortal. I ran around for five minutes with a stack of obsidian nuggets TRYING to die, and I could not. As long as you have fuel and the pet, you can't die, and the only way TO die is to somehow lose them. How is this balanced?

**Comment by capnkirok** [comment]
You are right. This should probably have a cooldown or be more expensive.

**Comment by crimsonDestroyer** [comment]
Worth noting, since this, I have found ways to die with the Enderman Pet. And by ways, I mean a way. If you fall into lava in the Nether, sometimes the constant sustained damage will be enough to overwhelm the pet and kill you. Sometimes. After a consistent 10-15 seconds minimum. Also, the void ignores the pet entirely and kills you regardless, so there's that (although it does protect you from /kill). Doesn't change that this is still incredibly powerful, but worth noting.

**Comment by Reshy** [comment]
I dunno Crimson, I just jumped into the void and it not only doesn't kill me, but it also doesn't consume obsidian.  It's exceptionally strong, enough that I may have to blacklist it until it's patched out.  At the very least it ought to consume 1 nugger per save, if not 9 since a feedbag can carry 1154 nuggets, even if that's 9 nuggets per save that's still 128 times you can avoid dying in a row without a refill.

**Comment by capnkirok** [comment]
I think cooldown timer (default 2 mins, but configurable, like Illuminati) + 1 nugget per save is more balanced.

**Comment by capnkirok** [comment]
Ok, I have a solution for this, I think it works well.

Enderman can only save you if you have more than 1/2 heart. If you are saved by Enderman Pet, you are then set to 1/2 heart and your Food level is set to no more than 5 hearts. So, you'll need to heal before the Pet will work again.
