### ISSUE TITLE
SMP Creeper & Squid Pet Issues 1.7.10

### ISSUE THREAD

**Issue by streamphotog** [capnkirok/Inventory-Pets#49]
Creepers go super fast once the ocelot pet is activated on a server. 

Squid pet makes you jump everywhere when it rains on a server.

Squid pet makes you go super fast in the ocean on a server.

**Comment by capnkirok** [comment]
Creepers go super fast once the ocelot pet is activated on a server.
**This is intentional**

Squid pet makes you jump everywhere when it rains on a server.
**I believe this is the missing piece of information from #42 ! Thanks! This is not supposed to happen.**

Squid pet makes you go super fast in the ocean on a server.
**Yes, this is also intentional, but might be a bit too fast at the moment.**

**Comment by capnkirok** [comment]
Squid pet will be slightly slower.

**Comment by capnkirok** [comment]
Fix to Squid will go into 1.4.0 (flying/jumping/superfast)
