### ISSUE TITLE
Chest Pets kick players from the server

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/Inventory-Pets#535]
Minecraft v1.19.2
Forge v43.2.14
Inventory Pets v2.0.18

When placing a chest pet taken from the creative inventory and placing it in the hotbar, the player is immediately kicked from the server with the message `Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128425_(String, int)" because "nbt" is null`. No other errors are mentioned in the log.

![image](https://github.com/capnkirok/Inventory-Pets/assets/12000593/5dddac83-d5c3-410b-b5c0-29d402834c8f)

**Comment by capnkirok** [comment]
Well, that's not good. I'll take a look tonight.

**Comment by capnkirok** [comment]
Looks like it applies to 1.18.2, 1.19.2, and 1.19.3. Still haven't found the root cause, but it only affects when dragging and dropping from the Creative Tab when playing on Server. Works fine if you /give to player. 

The "m_128425_" maps to "contains", so it's trying to parse the NBT data for a certain string when the NBT data is null. But the NBT data can only be Null because the item isn't officially instantiated until it hits the inventory. Very strange bug.

**Comment by capnkirok** [comment]
Ok, I found a workaround, but it will only fix 1.19.2 and 1.19.3. For 1.18.2, I've actually hidden the chests from the Creative Menu. Players will have to use the /give command.

**Comment by WenXin20** [comment]
Ah nice, thanks!

**Comment by Xplodin** [comment]
It seems this issue was also present when you open a refined storage grid and the double chest pet is in it
