### ISSUE TITLE
Chest Pet Dupe work around

### ISSUE THREAD

**Issue by Kerbal-Man** [capnkirok/Inventory-Pets#539]

**Comment by Kerbal-Man** [comment]
WHY DOES PRESSING ENTER MAKE AN ISSUE
you swap an item with the chest pet and it will pick it up and you can move it into another slot and do the exact same as if the patch wasn't there

**Comment by capnkirok** [comment]
Ok, I have this fixed on 1.19 versions and on the upcoming 1.20 version. Still working on 1.18, which handles this a bit differently.

**Comment by capnkirok** [comment]
Ok, 1.18 updated in Dev. You could be a game tester with those skills.

**Comment by qznfbnj** [comment]
Strange thing: In 1.19.2-2.0.19, Chest Pet can still be used to farm items, and when swapping Chest Pet and items will close the GUI.
## Farm items
Expected Behavior: can't move a Chest Pet that do have their inventory opened

https://github.com/capnkirok/Inventory-Pets/assets/100760086/55885f5e-8312-4928-87b8-6fd4dedf2735

## close the GUI
Expected Behavior: Items can be swapped with Chest Pet that do not have their inventory opened

https://github.com/capnkirok/Inventory-Pets/assets/100760086/58ce2717-97bd-4070-97ea-2886c0062edf
