### ISSUE TITLE
Inventory Pets conflicting with Mystical agriculture. 

### ISSUE THREAD

**Issue by EllensFish** [capnkirok/Inventory-Pets#585]
When i have both mods installed and I try to fly using the flight augments in the supremium armor in mystical agriculture, i am unable to fly. I double tap space bar to fly (creative flight) but nothing happens. When i remove inventory pets it then works properly.

**Comment by capnkirok** [comment]
Yes, Mystical Agriculture (it turns out) just checks to see if the player is wearing the armor and then allows flight (instead of adding an effect or a new capability which I can easily exclude). I can make an exception for this mod, though.

It's a shame as I tested many flight mods and just rolled out fix earlier today, but didn't test this one in particular.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev and will be in next release.
