### ISSUE TITLE
Anvil Pet "Replaces" players items, deleting them and replacing them with another item they possess.

### ISSUE THREAD

**Issue by Sourceshard** [capnkirok/Inventory-Pets#603]
Minecraft: v1.19.2

Forge: v43.3.13

Mod version: Latest Release 2.1.2.1

Used in the following Modpack: Monumental Experience 2.2.170

Bug Experienced:
When having the Anvil Pet in your inventory and it eats Iron Nuggets to repair your gear. 
A player on our server experienced a bug where an Item was "Replaced"
A diamond pick was deleted and replaced with a Carbon Copy of their "Elytra" enchants and all.
The player's items were restored and they continued to use the pet. The exact same occurrence repeated itself. 

A clip has been recorded. 
https://cdn.discordapp.com/attachments/133839601067491338/1256756631673503844/Untitled_video_-_Made_with_Clipchamp.mp4?ex=6681ed52&is=66809bd2&hm=20354df5bcb14576ef2ae5ccde283b5c32c06c31caf2a174b7e1e18e45709ad4&

I have not tested whether this occurs alone with this mod and its dependencies.

**Comment by capnkirok** [comment]
Ok, that's interesting. I just added the ability to repair worn armor, so it's most likely a bug on my side.

**Comment by capnkirok** [comment]
I'll aim to get a fix in weekend of July 6/7. If this becomes super annoying, you can temporarily disable the pet in the config.

**Comment by HatelessHeart** [comment]
The same thing is happening on my server, every time the anvil pat eats an iron ingot An item from my curios is being duplicated and I have lost two items I think because of this and they were extremely rare and highly modified and enchanted weapons... It must have duplicated at least 50 or 60 of these gloves that I'm wearing but now I'm realizing It might be deleting the things in my inventory and I just didn't know what was going on! This is on the latest version of inventory pets and Minecraft version 1.20.1 .

**Comment by capnkirok** [comment]
I'll have it fixed soon. In the meantime, you can disable the Pet to prevent this happening.

**Comment by HatelessHeart** [comment]
Ty

Branden Dickerson

**Comment by capnkirok** [comment]
Just a quick update, I won't be able to get to this until the middle of September due to RL. But it's on top of the list when I get back.

**Comment by HatelessHeart** [comment]
Thanks and it's all good I understand

**Comment by capnkirok** [comment]
Ok, this is fixed in the dev environment, should be released in the next day or so. Look for release 1.13.
