### ISSUE TITLE
[1.9] Pufferfish Pet not eating glowstone

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Inventory-Pets#73]
@capnkirok I tested the Pufferfish Pet against a swarm of spiders and it didn't eat any glowstone whatsoever. I am 98% sure this is a bug.

**Comment by capnkirok** [comment]
That's one powerful Pufferfish..... XD

**Comment by BellaRose0613** [comment]
ikr

**Comment by capnkirok** [comment]
Hmmm... did you mean glowstone dust? I don't seem to have an issue, and other reports are that is is fine. LMK 😄

**Comment by BellaRose0613** [comment]
I meant glowstone dust, sorry. Maybe Forge is messing with me. :b

**Comment by capnkirok** [comment]
Let me know what version of Forge you have... 1.9 has a few bugs

[EDIT] - got it from your other post, thanks!

**Comment by BellaRose0613** [comment]
Version release 1.9-forge1.9-12.16.0.1877-1.9

**Comment by capnkirok** [comment]
Well, he eats twice per minecraft day. One thing you can check to be sure. Go into the config file and change the value for Eat Timer Multiplication Factor to something like 5 (instead of 120). If the Pufferfish doesn't eat (regardless of mob fighting) within a minute or so, then there is for sure a problem.

**Comment by BellaRose0613** [comment]
Yeah, he eats. :b

**Comment by capnkirok** [comment]
Great! Thanks so much for testing again 👍
