### ISSUE TITLE
Pacman eats all foods qty goes negative - 1.9.4 Inventory pets 1.4.7.1

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#92]
While on single-player world shared to LAN, Pacman has eaten just about every kind of food and then some, even spider eyes. He also has eaten iron keys from 'lucky cases mod'.  He also keeps eating a type of food even if the count goes to zero thus having a negative number. He also starts eating as soon as one hunger goes away, causing him to eat a ton of food.

-Frobuzmumber

**Comment by capnkirok** [comment]
Yikes. Thanks, will take a look and see if I can fix this weekend.

EDIT: Technically, we should not be surprised by this behavior. He is Pac-Man after all.

**Comment by capnkirok** [comment]
Update:
- Changing the eating so it works after to 'drumsticks' are gone on hunger (instead of half of one)
- Negative amount bug fixed
- Seeing what I can do about 'sort-of' edible foods.

Edit:
- Made a backlist for vanilla poison foods, and also added a check to make sure there are beneficial stats. Hope that works for the iron keys. Why the mod author would classify that as ItemFood is beyond me.

**Comment by capnkirok** [comment]
This is fixed in 1.10, will roll it into the next round of fixes for other builds.
